name: genshintools
description: genshin tools
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.3.0
  dio: ^4.0.4
  flutter_bloc: ^8.0.0
  hydrated_bloc: ^8.0.0
  path_provider: ^2.0.7
  flutter_services_binding: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
  test: ^1.17.10
  pretty_dio_logger: ^1.2.0-beta-1
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/genshindb/
    - assets/images/
    - assets/
