// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ_-BK-ffNdfEc604VuaeV6MFpK2Wcp3k',
    appId: '1:467073950595:android:68168a26909f99d39bccb6',
    messagingSenderId: '467073950595',
    projectId: 'genshintools-d7c57',
    storageBucket: 'genshintools-d7c57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1yksJw2a-2TTZsVTJ1XFnDueCGalk4Fo',
    appId: '1:467073950595:ios:d83d837499c7b9639bccb6',
    messagingSenderId: '467073950595',
    projectId: 'genshintools-d7c57',
    storageBucket: 'genshintools-d7c57.appspot.com',
    iosClientId:
        '467073950595-3ja8q6460549v8smv8cfufar82i9tcji.apps.googleusercontent.com',
    iosBundleId: 'dev.morlay.genshintools',
  );
}
